---
- name: create a stack, pass in the template via an URL
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: present
    region: "{{ region }}"
    disable_rollback: false
    template_url: "{{ TEMPLATE_URL }}"
    template_parameters:
      VpcCIDR: "{{ VPC_CIDR }}"
      PublicSubnet1CIDR: "{{ PUBLIC_SUBNET_1_CIDR }}"
      PublicSubnet2CIDR: "{{ PUBLIC_SUBNET_2_CIDR }}"
      PrivateSubnet1CIDR: "{{ PRIVATE_SUBNET_1_CIDR }}"
      PrivateSubnet2CIDR: "{{ PRIVATE_SUBNET_2_CIDR }}"
      TagEnv: "{{ TAG_ENVIRONMENT }}"
    tags:
      Stack: "{{ stack_name }}"
